### ISSUE TITLE
Código Fonte

### ISSUE THREAD

**Issue by henriquerick** [killerall/advtec-logprofiler-reader#1]
Olá,

Não sabia qual era a melhor forma de entrar em contato, então pensei em abrir uma issue rsrs.
Estou desenvolvendo um protótipo, que analisa os logs gerados pelo appserver, para meu trabalho de conclusão da faculdade.
Seu projeto me ajudaria a entender como montou a estrutura dos meta-dados contidos no console.log. Poderia compartilhar o código fonte?

**Comment by killerall** [comment]
Desculpe a demora, não vi notificação e atualizo muito pouco esse repo.

Eu não consigo abrir o codigo desse projeto.

Posso tentar explicar +- como fiz.

O Console.log é analisador por um parser escrito com Antlr (https://www.antlr.org/) 

Porem como a parte do profiler do appserver é bem especifico, consegui ler o mesmo. Com o Antlr, para analisar o log inteiro, creio fique meio inviável por conta da falta de estrutura do contéudo.

**Comment by henriquerick** [comment]
Obrigado pelo retorno.

Queria entender se o trabalho que estou desenvolvendo possui alguma semelhança direta com o seu trabalho do log profiler reader

Em geral, meu trabalho irá abordar a leitura dos thread erros que aparecem no console.log do appserver. Após identificar as variáveis, meu objetivo será apresentar onde está o problema diretamente no código.

Basicamente vou precisar criar um intepretador do log para extrair as informações?

________________________________
